// ДС-React — компоненты дизайн-системы (CONCEPT §3.4, слой «ДС-React»). Импорт: `@replai-smm/design` (README.md).
export { Stack, Inline, Grid, Page, PageHeader, Section, SurfaceProvider, type Space, type StackProps, type InlineProps, type GridProps, type PageProps, type PageHeaderProps, type SectionProps } from './components/layout'
export { Button, ActionArea, RowContext, ExternalMark, type ButtonProps, type ButtonVariant, type ButtonSize, type ActionAreaProps, type PrimaryAction } from './components/Button'
export { StatusBadge, ToneIcon, type StatusBadgeProps } from './components/StatusBadge'
export { ToneTag, type ToneTagProps } from './components/ToneTag'
export { StateView, Skeleton, Loading, type StateKind, type StateViewProps } from './components/StateView'
export { DataTable, List, compareSortValues, type Column, type SortDirection, type SortState, type DataTableProps, type ListProps, type CollectionProps } from './components/Collection'
export { FilterBar, SearchField, useUrlFilters, type FilterDef, type FilterOption, type FilterValue, type FilterBarProps, type SearchFieldProps } from './components/FilterBar'
export { Tabs, type TabItem, type TabsProps } from './components/Tabs'
export { Card, type CardProps } from './components/Card'
export { Drawer, type DrawerProps } from './components/Drawer'
export { Notification, Toaster, useToast, type NotificationProps, type NotificationTone, type ToasterProps } from './components/Notification'
export { Dialog, ConfirmDialog, ConfirmProvider, useConfirm, type DialogProps, type DialogSize, type ConfirmDialogProps, type ConfirmOptions } from './components/Dialog'
export { TextField, TextArea, type TextFieldProps, type TextAreaProps, type FieldBaseProps, type FieldSize } from './components/TextField'
export { Select, type SelectProps, type SelectOption } from './components/Select'
export { Checkbox, CheckboxGroup, type CheckboxProps, type CheckboxGroupProps, type CheckedState } from './components/Checkbox'
export { NumberField, type NumberFieldProps } from './components/NumberField'
export { FileField, fileSizeText, acceptText, fileMatches, type FileFieldProps, type FileFieldHandle } from './components/FileField'
export { Combobox, type ComboboxProps, type ComboboxOption } from './components/Combobox'
export { Avatar, type AvatarProps, type AvatarSize } from './components/Avatar'
export { CountBadge, countText, type CountBadgeProps, type CountTone } from './components/CountBadge'
export { Tooltip, type TooltipProps } from './components/Tooltip'
export { STATUS_IDS, TONE_ORDER, statusOf, toneOf, type StatusId, type Palette, type Tone } from './lib/status'
export { ChatThread, type ChatMessage, type ChatThreadProps } from './components/ChatThread'
export { ReplyBox, type ReplyBoxProps, type ReplyBoxHandle } from './components/ReplyBox'
export { ThreeColumn, type ThreeColumnProps, type ColumnIndex } from './components/ThreeColumn'
export { WeekCalendar, mondayOf, addWeeks, weekTitle, type WeekCalendarProps } from './components/WeekCalendar'
export { ProofreadGrid, GridLegend, GRID_TONE, GRID_TONE_LABEL, type ProofreadGridProps, type GridColumn, type GridCell, type GridTone, type GridLegendProps } from './components/ProofreadGrid'
export { StatTile, Delta, type StatTileProps, type StatTileCompare } from './components/StatTile'
export { ChartFrame, SERIES, SERIES_BG, seriesVar, resolveSeriesColors, useSeriesColors, type ChartFrameProps, type LegendItem, type SeriesLine } from './components/ChartFrame'
export { Steps, stepState, type StepsProps, type StepState } from './components/Steps'
